import q_img from './img/keyboard/q.png'
import w_img from './img/keyboard/w.png'
import e_img from './img/keyboard/e.png'
import r_img from './img/keyboard/r.png'
import t_img from './img/keyboard/t.png'
import y_img from './img/keyboard/y.png'
import u_img from './img/keyboard/u.png'
import i_img from './img/keyboard/i.png'
import o_img from './img/keyboard/o.png'
import p_img from './img/keyboard/p.png'
import a_img from './img/keyboard/a.png'
import s_img from './img/keyboard/s.png'
import d_img from './img/keyboard/d.png'
import f_img from './img/keyboard/f.png'
import g_img from './img/keyboard/g.png'
import h_img from './img/keyboard/h.png'
import j_img from './img/keyboard/j.png'
import k_img from './img/keyboard/k.png'
import l_img from './img/keyboard/l.png'
import z_img from './img/keyboard/z.png'
import x_img from './img/keyboard/x.png'
import c_img from './img/keyboard/c.png'
import v_img from './img/keyboard/v.png'
import b_img from './img/keyboard/b.png'
import n_img from './img/keyboard/n.png'
import m_img from './img/keyboard/m.png'


export default [ 
    {name: a_img, letter: 'a'},
    {name: b_img, letter: 'b'},
    {name: c_img, letter: 'c'},
    {name: d_img, letter: 'd'},
    {name: e_img, letter: 'e'},
    {name: f_img, letter: 'f'},
    {name: g_img, letter: 'g'},
    {name: h_img, letter: 'h'},
    {name: i_img, letter: 'i'},
    {name: j_img, letter: 'j'},
    {name: k_img, letter: 'k'},
    {name: l_img, letter: 'l'},
    {name: m_img, letter: 'm'},
    {name: n_img, letter: 'n'},
    {name: o_img, letter: 'o'},
    {name: p_img, letter: 'p'},
    {name: q_img, letter: 'q'},
    {name: r_img, letter: 'r'},
    {name: s_img, letter: 's'},
    {name: t_img, letter: 't'},
    {name: u_img, letter: 'u'},
    {name: v_img, letter: 'v'},
    {name: w_img, letter: 'w'},
    {name: x_img, letter: 'x'},
    {name: y_img, letter: 'y'},
    {name: z_img, letter: 'z'}
]